openapi: "3.0.2"
info:
  title: GA4GH Discovery Search API
  version: 0.1.0
  description: |
    Search is an API for searching biomedical data.

    More information on [GitHub](https://github.com/ga4gh-discovery/ga4gh-discovery-search).
  license:
    name: 'Apache 2.0'
    url: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-discovery-search/develop/LICENSE'
  contact:
    name: 'GA4GH Discovery Search Team'
    email: 'ga4gh-discovery-search@ga4gh.org'
security:
  - bearerAuth: []
paths:
  /tables:
    get:
      summary: List Tables
      description: Returns a list of Tables.
      operationId: listTables
      responses:
        '200':
          description: A list of Tables
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTablesResponse"
        '500':
          description: An unexpected error occurred
  /table/{table_name}/info:
    get:
      summary: Get a Table
      description: Returns the information about the Table identified by name.
      operationId: getTable
      parameters:
        - name: table_name
          in: path
          description: Unique Table name, unique to this implementation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A Table
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Table"
        '404':
          description: This server does not implement the data operation
        '500':
          description: An unexpected error occurred
  /table/{table_name}/data:
    get:
      summary: Fetch data from a Table
      description: Optional operation that returns data from a Table
      operationId: getData
      parameters:
        - name: table_name
          in: path
          description: Unique Table name, unique to this implementation
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Data from the Table
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableData"
        '404':
          description: This server does not implement the data operation
        '500':
          description: An unexpected error occurred
  /search:
    post:
      summary: Perform a search on Tables
      description: Optional operation that accepts a Query and returns a TableData
      operationId: search
      responses:
        '200':
          description: Query results returned as TableData
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableData"
        '404':
          description: This server does not implement the search operation
        '500':
          description: An unexpected error occurred
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    ListTablesResponse:
      required:
        - tables
      type: object
      properties:
        tables:
          type: array
          items:
            $ref: "#/components/schemas/Table"
        pagination:
          $ref: '#/components/schemas/Pagination'
    Table:
      required:
        - name
        - data_model
      type: object
      properties:
        name:
          type: string
          description: Table name
        description:
          type: string
          description: Optional description of the Table
        data_model:
          $ref: "http://json-schema.org/draft-07/schema#"
      description: |
        Describes a Table hosted by this search node.
    TableData:
      required:
        - data_model 
        - data
      type: object
      properties:
        data_model:
          $ref: "http://json-schema.org/draft-07/schema#"
        data:
          type: array
          description: Page of JSON values, each adhering to the schema given in the "data_model" property
          items:
            # Each item must conform to the schema provided in the "data_model" section of this Table.
            # Not sure if this constraint can be expressed in OpenAPI 3.0.
            type: object
        pagination:
          $ref: "#/components/schemas/Pagination"
      description: A paginated collection of tabular data
    Pagination:
      type: object
      properties:
        next_page_url:
          type: string
          description: URL pointing to the next page of the same Table. Null or absent on last page.
          format: uri
