openapi: 3.0.2
info:
  title: GA4GH Discovery Search API
  version: 0.1.0
  description: >
  Search is an API for searching biomedical data.

  More information on:

  - [GitHub Pages](../)

  - [Full Discovery Search Specification](../SEARCHSPEC.html)

  ### Overview

  The primary container for data in the Search API is the **Table**. Tables contain rows of data, where each row is a JSON object with key/value pairs. The table describes the structure of its row objects using [JSON Schema](https://json-schema.org/). Row attributes can take on any legal JSON value, eg. numbers, strings, booleans, nulls, arrays, and nested JSON objects.

  The API supports browsing and discovery of data models and table metadata, listing table data, and optionally querying table data using arbitrarily complex expressions including joins and aggregations. The query language is SQL with domain specific functions to facilitate informative typing of the result fields. 

  license:
    name: Apache 2.0
    url: >-
      https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-discovery-search/develop/LICENSE
  contact:
    name: GA4GH Discovery Search Team
    email: ga4gh-discovery-search@ga4gh.org
  x-logo:
    url: 'https://www.ga4gh.org/wp-content/themes/ga4gh-theme/gfx/GA-logo-horizontal-tag-RGB.svg'
security:
  - bearerAuth: []

tags:
  - description: The Discovery and Browsing part of the Search API consists of the following REST operations
    name: Discovery and Browsing
  - description: >
      The Query part of the Search API consists of the following REST operation:
    name: Query
paths:
  /tables:
    $ref: paths/tables.yaml
  '/table/{table_name}/info':
    $ref: 'paths/table@{table_name}@info.yaml'
  '/table/{table_name}/data':
    $ref: 'paths/table@{table_name}@data.yaml'
  /search:
    $ref: paths/search.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
